// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWebApi.Data;

#nullable disable

namespace SimpleWebApi.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260204200205_Employee Data Added")]
    partial class EmployeeDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleWebApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("JoiningDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            DateOfBirth = new DateOnly(1990, 1, 20),
                            Department = 1,
                            EmployeeId = "1001",
                            EmployeeName = "Alice",
                            Gender = "Female",
                            JoiningDate = new DateOnly(2024, 6, 20),
                            Phone = "953678982"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            DateOfBirth = new DateOnly(1999, 3, 11),
                            Department = 2,
                            EmployeeId = "1002",
                            EmployeeName = "John",
                            Gender = "Male",
                            JoiningDate = new DateOnly(2020, 7, 22),
                            Phone = "784778993"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            DateOfBirth = new DateOnly(2000, 5, 20),
                            Department = 1,
                            EmployeeId = "1003",
                            EmployeeName = "Molly",
                            Gender = "Female",
                            JoiningDate = new DateOnly(2026, 6, 20),
                            Phone = "34333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
